# Generated by Django 3.1.2 on 2020-10-30 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x_coord', models.FloatField(verbose_name='X Co-ordinate')),
                ('y_coord', models.FloatField(verbose_name='Y Co-ordinate')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(blank=True, max_length=250)),
            ],
        ),
    ]
