# Generated by Django 3.1.2 on 2020-11-20 04:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotzone', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_no', models.IntegerField()),
                ('confirmed', models.DateField()),
                ('origin', models.CharField(choices=[('L', 'Local'), ('I', 'Imported')], default='L', max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('hkid', models.CharField(max_length=9)),
                ('dob', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Virus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('disease', models.CharField(max_length=150)),
                ('max_infectious', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_from', models.DateField()),
                ('date_to', models.DateField()),
                ('category', models.CharField(choices=[('R', 'Residence'), ('W', 'Workplace'), ('V', 'Visit')], default='V', max_length=9)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotzone.case')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotzone.location')),
            ],
        ),
        migrations.AddConstraint(
            model_name='virus',
            constraint=models.UniqueConstraint(fields=('name',), name='unique-name'),
        ),
        migrations.AddConstraint(
            model_name='patient',
            constraint=models.UniqueConstraint(fields=('hkid',), name='unique-hkid'),
        ),
        migrations.AddField(
            model_name='case',
            name='infected',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotzone.virus'),
        ),
        migrations.AddField(
            model_name='case',
            name='locations',
            field=models.ManyToManyField(through='hotzone.Visit', to='hotzone.Location'),
        ),
        migrations.AddField(
            model_name='case',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotzone.patient'),
        ),
        migrations.AddConstraint(
            model_name='case',
            constraint=models.UniqueConstraint(fields=('case_no',), name='unique-case-no'),
        ),
    ]
