# Generated by Django 3.1.2 on 2020-11-22 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotzone', '0003_auto_20201121_1259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='locations',
            field=models.ManyToManyField(to='hotzone.Location'),
        ),
    ]
