# Generated by Django 3.1.2 on 2020-11-22 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotzone', '0004_auto_20201122_0813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='locations',
            field=models.ManyToManyField(through='hotzone.Visit', to='hotzone.Location'),
        ),
    ]
